version: "3.7"
services:
  mongo:
    image: mongo:4.1
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - "27017:27017"
  api:
    image: "node:11"
    user: "node"
    working_dir: /home/node/app
    environment:
      - MONGO_HOST=mongo
    volumes:
      - .:/home/node/app
    ports:
      - 80:3000
    command: "npm install && npm start"
    depends_on: 
      - "mongo"